### PR TITLE
Update browser support

### PR DESCRIPTION
**Pull request by tysongach**
Quick update; the triggers:

- Transitions for Chrome, Opera and Safari
- [Box sizing](https://github.com/thoughtbot/bourbon/pull/568) for Firefox

### CODE REVIEW

**Comment by joshuaogle** [comment]
Looking forward to some cleanup for 5.0 with this :+1:

**Comment by joshuaogle** [comment]
How would you feel about bumping Opera to 15 and getting rid of the `-o` prefix? That's when they switched to supporting `-webkit` instead and `-o` is now treated as an alias.

**Comment by tysongach** [comment]
Oh! Nice. Link to source/doc/explanation for that? I’d be game.

**Comment by joshuaogle** [comment]
[This article](http://www.sitepoint.com/opera-css3-webkit-prefix/) talks about the switch and aliases. You can also see the switch on pages like [CanIUse's transform page](http://caniuse.com/#search=transform) if you click "Show all". [Their page on flexbox](http://caniuse.com/#search=flexbox) shows that it became unprefixed not long after, but Safari still requires the `-webkit` prefix anyway so it doesn't matter.

**Pull request merged**
