### PR TITLE
Adding package.json

### PR DESCRIPTION
**Pull request by NickHeiner**
I would like to consume bourbon through npm. Adding a package.json allows that to happen.

I wasn't sure what to put for the version field.

### CODE REVIEW

**Comment by niksy** [comment]
Any progress on this? It would be useful if bourbon is available on npm so anyone using it can target it with proper semver ranges, and as @genexp mentioned, libsass is gaining traction, so it would be nice to "jump on that train".

**Comment by tysongach** [comment]
@niksy Thanks for the reminder. I put an Issue over on Tonic asking if he would let go of the Bourbon name on npm: https://github.com/tmrudick/tonic/issues/6

**Comment by tysongach** [comment]
@NickHeiner @genexp @niksy Boom. We are now `bourbon` on npm: https://www.npmjs.com/package/bourbon

**Comment by genexp** [comment]
Boom!

**Comment by niksy** [comment]
:sparkles: Awesome! :sparkles:

**Pull request merged**
