### PR TITLE
Reorganize core files

### PR DESCRIPTION
**Pull request by tysongach**
- ~~`support`: library set up~~ `helpers`: sort of like “constants” for the library
- `settings`: library settings
- `validators`: simple functions to validate things
- `utilities`: help build features of the core library
- `library`: core user-facing library

### CODE REVIEW

**Comment by joshuaogle** [comment]
`settings` and `support` seem awfully similar and each have only one file. I think it would make sense to move `scale.scss` into `settings`. Other than that I like having it split up by purpose and the names look great :+1:

**Comment by tysongach** [comment]
@joshuaogle Yeah, I’m not super happy with `settings` and `support`. The reason I broke them out is because `settings` _uses_ the stuff in `scales`… :confused:

**Comment by joshuaogle** [comment]
@tysongach There's nothing wrong with importing the files in a specific order. Or at least, I don't see a difference between that and importing folders in a specific order. Either way is fine with me, just trying to keep it simple.

**Comment by joshuaogle** [comment]
Yep, that looks better to me too. LGTM :+1:

**Comment by tysongach** [comment]
Thank you, @joshuaogle!

**Pull request merged**
