### PR TITLE
Update logo to new version

### PR DESCRIPTION
**Pull request by whmii**

### CODE REVIEW

**Comment by tysongach** [comment]
Screenshot?

Probably gonna wait until we get the website fleshed out, as it is still a work-in-progress.

**Comment by tysongach** [comment]
Closing for now.

- The SVG asset being linked to has an embedded image and needs some major clean up.
- I’d like to step back and work on the brand as a whole before we just inject a logo out of the blue.

**Comment by tysongach** [comment]
Here’s the current SVG code:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg width="100%" height="100%" viewBox="0 0 800 200" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;stroke-linejoin:round;stroke-miterlimit:1.41421;">
    <g transform="matrix(1,0,0,1,-1,46)">
        <text x="168.252px" y="87.235px" style="font-family:'QuincyCF-Text', 'Quincy CF';font-size:162px;fill:rgb(51,51,51);">B<tspan x="267.882px 345.966px 433.446px 495.654px 579.894px 656.358px " y="87.235px 87.235px 87.235px 87.235px 87.235px 87.235px ">ourbon</tspan></text>
        <text x="171.739px" y="136.735px" style="font-family:'SFUIDisplay-Regular', 'SF UI Display';font-size:44px;fill:rgb(153,153,153);">bourbon.io</text>
    </g>
    <g transform="matrix(3.375,0,0,3.375,16.7088,15)">
        <clipPath id="_clip1">
            <rect x="0" y="0" width="40" height="40"/>
        </clipPath>
        <g clip-path="url(#_clip1)">
            <g transform="matrix(0.296296,-0,-0,0.296296,-4.95074,-4.44444)">
                <clipPath id="_clip2">
                    <rect x="16" y="15" width="136" height="135"/>
                </clipPath>
                <g clip-path="url(#_clip2)">
                    <use xlink:href="#_Image3" x="16.709" y="15" width="135px" height="135px"/>
                </g>
            </g>
        </g>
    </g>
    <defs>
        <image id="_Image3" width="135px" height="135px" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIcAAACHCAYAAAA850oKAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAgAElEQVR4nO2debTlVXXnP/t37ytqpNCO0PAeaJwgnZhEoyw7K1K8oii603aGXq6omTpqaxApZicos1YnaaQZghMIpajLmKbTMaa7s7o1DFVUFQ44RFevmIbCVpv3ABtDpICihnt/59t/nLPP79xbBdx73331Crl7rar33v3d3xn32fPeByYwgQlMYAITmMAEJjCBCUxgAhOYwAQmMIEJTODZCraUnYfNG9sKOtrM1gLHAGupbCVBUxhTiDYwpaApIP6Ln09ZZflzq2xKUvzcbEpS27+nwJRVTKlO323blLpFe5VNofy3mVlXtTqSulZZR7W6QMda1sHoIjoSXYMO0BV0kDpAF6xjFV0FdTDrILpIHSrrqhs61rKuAh2z+C6VdZC8zQPAo1axO3T1aNW23aq1e9m1W/cf/p2JsCjIES7duJoWJ1JzEsZJVHYi0kmIk4DjgLUYxyBW+TsSVC0j1MIMFJRHZxiSQL0jVhAAVbtCtbDKCHVID5sZWmXxectQ4KD283fT9yB9J31uLYNacQxm+X0zA2/Lx6bYDt6+4vuqm78xcj/eLwKrms9z38Z+YLfEP5pxP2b3AXMEzQnmzJgD5pZdu/WxUffryWDByBE2b5wBXo14NcargX8GPCd3UBmhq7QucQMzCKT4mVlEDEiLTnwGoBARR0GoFtVUFX8PYC3y5ua+DKjieyi2F9tKG3sQoqVfVGwYxUdKg8XSBqvBnoQMVqX5+LgOsbLWiuNDjqixTQVRtSwjj4IjumK7xPbDgRARtRiXtSIiCh4Gvm7GXap1F8aXj/rgth8NuI2HhJGRI2ze+DNmdq2kDXGByJsauj6pNIHK8ikvT0/PM4ub6afHTztVQTlovpNPYGg2zaq4YX5KzSzvq4+nPJmZgkCmCP3QgxxOFRyJfB7+Yvm9NJ84Dn/WQxEywsbBFMjtB6h4D9RL9YoxKyFUVaX5xvXcA1yhwDXLP7xt79Nu6CFgaOTQ+856DsYfqtbbMVr5QFmzyY4sBPIJ8U00I5NVq6wHcVSc8nzafYFbhrrKJNtJfHoxt63yNPvaJuqk4OyAng20it6NUDOWjIAlO6mswY/EBn0NnC366iodAP9uZpWOPDRt5jVOY5QvZx5/mrP/pP+9Yh7Nzzng4qM+sPUvht3roZAjbN5oGJ837CxftIZk+4wTz67iZopEDXwTIJNO/35ewCCsbWnR/AQW5LtcvESG1U1yx1SUO/JYaDaz/7Tn/sqxhqKDontnAYjeUy1lGaVqWx5XRh5nLSX+hsgSQ1e9HVGMr0R49b1fjtX78SWqlWUXHxu+xCB19UvLP7LtSwNsc4bq6b/SgFX224adledU8EeFOPk85eCkslgExUmUiFGuB8XC+6lqyHk8QRkxoIeqBGclrSi/ZPaCU37LCFa1nKfFzhvK5RMtxAwiAjpyR5aW3vUTXqfxZjbpByLNORSyb1DRUcOK5bscCoT1d5qhZoqbxxji4eqlqM2LoRYIsxY37T9//fKn2t9+aA/6Rf3BWceqqw84OpkllpA2IS6cs5C0iE7a0yL5afcT7ycSGpKrYKl9560WgI6JjrWqDqiTVL8OrjIaHQIdoJPVSOgIOlVlHUVVswN0rLKOgjoK6phZB1PHKuuEWh0zpFptjDbKqnObylxlbiOmJNrWqNZtBaaqFlOhozZmU6A2Vk1ZxRSVtS1oSkFT1rJ2biep6BJtR+isqdUCFzzTAZCvecs3JLHavEHpcAicErlIYxWEDqdYi8uA9w265wOzlbB5438ALu098Y3Q2HyxaTWSb6RaD2LMGXYfxpykf7DKdqur3VbZIxi7FbQb2I3xOOKAb1j7ilsDP8Zw4ML1Zi1rhY5WWMVaos3naKS1wFrEWoy1qnUclZ1ocKKkE83shBAUaa2rzn4Y5Qe0FGwF2AFJxyz/0GAC6sCUwyr7qdAVVTttussaTjG62mNt+6rQVxT0bavsPoP7CDzQev+tnSHX7FkDy67dKqALPJb+zQ/y3oEL17etshMQJ1rFi8B+QfAqwSsQR7nqH9mfv6VlZpwKbB+kj4GRA/Hiyo050CMVq9bHrWVn2x/+TT1wexNYECy7dmsXuC/9+yLwaYB9m2ZPsYq7FHR0o1UlmQog8AsMiBwDCaR631mG8eJS5VIhVEncaH80QYwjAZZ/eNvdCtwtkYTRUpMEYPWgbQ1EOSQdB6zol1Dc1GAVE7ZxBIFVdErVH5cNo4a1ctB2BlVl9zrfKlU8N00jJlTjSALF3VKxTy4bUtkjgzYzKHI8CjxhbiVMptyqXUXJWDx3yOFPYBFBYjpb5qPfpTE8DijwwoDIUf3xLcJ4ECB0Q3KUFUYpeMHwU5jAYsD+82YrjBOhsVP0Ojt1/6BtDWwhtcoekBSphVvlklVQ0gsGbWcCiw7HG0yVIQfqhvyHNGbKAaCgB9z8XcZKRIeUPX/goU9gUUFBJ5ZW09IKDWDG+CkH4v5sOm813lWrQGhm4HYmsNgwk/0y7rTKPit+tPwjdzwxaEODI0dl81ljce+nO5uwCXIcIWCVTRPlwOzAjOYGAzQwS4Fh2Eod5t0jau4arrI0PEGOIwdmVIYlEI1hSeQYmKXAEMhRtau5HJ2VXcLuneXosHnj0cN0PIHFAYmZHPXmsR3Kfy8O5QjdSJI80spajeNNQair6WE6nsAiQdB0joXx6LsqsRazxaEcwA8kwkER13icgZ04TMcTWCSwKJCm37OPIxnFFodytC6/pWsVD6pWdgHneA5A9URjWWrYf96sAdNlALKHSKYItMVBDgDEfIw+8hAjUtCRYCKULj2Y/QSwrD8UsYisXzS2goLmcipAxkacvUyQY4lBdZghsvie2NhsHQ2LxFYArGXzSV9OH/ioAJsgx1KDtarpMkfGcnggWGV7MQb2yMIIbMUpheecOGtBTATSJYbQDTMltchaSwxenl9x3R160pcPAcOxFTHfk6taC3PZo5pYSY8AmPb0SDCqlAMU92k4lgJDUw7NeXhg6LrKQkxXDDqmfu+ZA4egTWD8YMZM6Ma0BnmyWPZ/DSeMwrDIAfOehJMTej15Kdo+JoawpYWZqmWoE3orCcQIrUWmHPCgaikHqyYOFnLZgglrWUqwyqZDt8kIzJmVMelscSlH6/23dqjsB9Ck5OVBTDSWJQfBTEaMyrJl1Krh/SowPOWA4D4WmrxX8PyVicayRLD3nNOPptaaGPWVPkyHNomJhwE5YA6R0++a3Eew1oStLCFMZ/nCk7s9AS3u16ILpMjt8ynjvCwmIk3YylKBtWxGqR5K6LqSYF7loEtlDw3b5uDpkAmqdjUfuqGnLocH/9jEhL50IE17lYOcJ+tgPLjiujuGzi0aGjlCrXkfRE6NdB/LxBC2lDCTS2PFeg3x05ivMrS8ASOwFUsyh9s7ygcE/ZPuuzcMnG43gfGBs3RnJeX2VJUdHuTAiM63iiI51/JorLKJIWwJwIxpd7S5ybwprzm8MAojIUdMbqIoqWItypJPE9ayBKBaM41dw3I6QqoVdngoR+vyWw6o1v+LCKJU9omSx02QY2kgU+wc5+uWhsNGOQBzTHTLaBF5NAkXPPzwxNnrllvLntdT6jNBKs53mGQOQNJczl2x8p9NTOhLANayEwC8zGRZ+jPVhz18yGFm8/Kyhh5OmounToJ+DjeYpaBig5iKUIRxxmy3B0Zpd2g7RxxN47oP3VRWuakq+GNLOcLmjS9V0OvN7GjEI4L/1Lr8lu8t9biAGbCmRqnX5AAQD624/o4DozQ6GnKIeacaVQosyYXefwwF0vrSM1vAFnX1Zms3ZbYN/n196ZmfNuyC6vJbHl2yASoKo02+ijUFdEcURmFEtgLMk0voAqEJLBE8r/vuDUNVyj2SIVy20czsv5jZm2MInmsDQlKLwJtCrb/tvnvDy5dqjDkFMldr6SnYMpK8AaMjxxx4SiRNDYikPqnWCaMO6IgD453Av/HKAvlakKaMErEOKF/uXHLGOUsyRmmmqZuiHEqRzu7hRQ4FPdCkRCbBp6IUgH4shNL6PWe+SkF/7PXEYyJ5fJZrvoNH4x8Fdl33XRv+vPPODYc3qdxsOuepeGaA4SUyDi9baV952z6CfliSMcxSSShQeObbOur3nrkG42Yzm2oK3jfXZeSKA+mmhNDJd8z8hhnf6Fx8xs8ftsEaMz23K2RVFqgOP1uJSbnRE0t5G0JcvGe+d9Yq+yhmL0q/xzjZJG807KTJ3em5Y6XWiyW+0rnkjLMXe5z7zj29RdDxZuSKS6W7ftjM+hJGRw4xJwF1Y6otqvQ/o5EjXLbxdyR+y1mmvFKOgzUXDAWfv1/z4QcGjgI+2nnnhps7F5+xZtHGWus4QcupmCdPq6F2h59yKGjesRW/b8U9gs9gdTZctvHFwHVAYpHpQbrvxdLNBOAkPP0eHJFytLeznTdIfOPARWf83KIMWMzEshiFo61gg4dd5oBoJU1pdqB4W1HOaXmGUo760o1TCrpZtdZEL3P2F0VBtLh2y8Ev3cnBTylzw8ywdi6x8xLQVw5ctP73F2HY0xkxY2f5wiCr7NGVN24f+dbI0SkHzKPmVkO/KSmVGXpmaivS5Riv9D/zVV/WsM2eCwT7Xi+v5wq1UDekGx4NBZYjbjhw4fo/23/B+nFmBs5kIRmwVlYKGLYeRz+MTjlg3ivz91yVGfnxcd13bVi2kIEdbui+e8NGxMXZyJW8m+VVnaWhKaUYZoTI1Qdc9iquKMuCuhkK/KYZ39h/3uzPjmPcVoRmloJykjtGZimwMG1lLmNsKYw2KtUzxhBWv+fMtWb2KUi3YJUUwn+mqs2NnQNyEViyazw9LNmO9XwfIHT1UuAr+8+bfesYhj+de6t65Y5hyzz1w0KQ4355LAdkYTQ+s2dUJHrrilt3Y5yMcbrBJZj9nYch5Mj6xDKbi/08XsH/To2l4F4P8s0bV+SUJFiB2ZZ9m2Y/s/+82dHZjEW2YoVJwSrivgxZrKUfRkaO9n+8ba8ZDzsZzapcPjzPLENY6/23PtZ6/63bW1fceg3GyxHvCl3tcbYREd+azXdK0GMpLeQuQHXoSSxSN+S4zgzSb2F8fd+5sy8bZdzq9lYP9Ko+CRGXiK1A1qEjX82DBZ7ZJvT2Fbd221fedpUZP2MV9zd34ubCazkET3KWEVlOlkGsj6UULNhvblQdhTXVOhl01/7zZt84zDifOHudeZah35+roNguNBF7I8KCkMNaNtdTewpKHvyMohyHgvaVt31fQa8z40C8g76YH8WBcEHQA60TW3He38TbEuWCJlK/6cxsBfDpfZtm/+Wg47PKnqug5X4JcQ9IqB7dXQ+jxnN4/12l6oKNIGRtl06PbJmjvnSjmfGLCnoTxnNV60HEn7WvvK3n1uapq2//SueSMzZZxY1Ac/Ozp4BmtqGGvfqN0S1rLhxO4oa6fiF9oh5uXY52irZVdvPed5z+T1dcd8e+p5uDak1nk7lfugxItmC/CiwQOahsPl7hnU5Bvr7BYIlvUui+c8MJGKcAX21fedvj5bOweePLFXSzxMnuN0mOtHO679rwV8Bvtq+8rdkc8TGJy6ziJJcpcmR3cWCLJLP40y8M9gsEklDq3t0oONJsajRmrUW8Fvjs007SmMmakcea5I7YT62Hh1y2HlgQcpg1NcJyCUrnxWHxKUf9njNXUPESxCnAyRInI52CeCmwRkH/28x+uued9575YtX6gpkdm2+aMtKV5ALj14E/7Vx8xuunrrk9AExdc7s6F5/xWcRFruomC2T2sxycn5oWpjdnNSOBGw7jnbyhV0iFVzAAclhl081N3j4GF5q5f+WWHXq6Np4KFsZWQmIrTWZVZDEReY/vXHLG1NTVty/45siweePzgJcpcIoZJ6vWyRinWGUnqZYpKJqqQ/CFcVP3B9pX3aainaMJ/I2Cjg2hvOi6kRbjBut1iF8E7sxzFX8BXEQTs1IUno/mdQ+dbJRcklrfsBAC0U8Ti7hlQTJe6JzltT2DrIuCZkhqa7LCYq0oFBsLE0ZhoZSjZXP5FoU0+apyC6OZah1PvBR3JAibN24ELkGcoaAqM++qj56T1MT0Ufrao2b2p73f0RswXljMIGkM9Npp4hH/bQrkMOMuBT0msSbz+ETK8YoDjhU1jagvufbbGMpcuzGaOielxhf0zUHWR0EzVbuK7aRh5yDjBVpHYcGqbDMAeakwr9RvLMgBp/ed9SbgfypwJtAghgtwtQid0Fugvzee4fvtK2/rvbPd+LelVSqyFNdH06eustZ6dfnq1DW3i8ruLe056jY3L2bDVxpHZq8QNRW/80RCISTnGFiryraxOK/w91bZ5wdZI2tZrnOeQwMdwRboV4EFIsfUVbftAX7kru3GQurC1WjIETZvfIlqfVxBrZykU/gr3AOag238ejGa06lDCGOq9ZPZg5kMVKGsgAPxREch8SWp0Hz5bFf+1VVUf6mULTx0IZApS4pWbyyn6f2YTqr8mrWqC1d8dPtgsoKHRsgPhuXUhIXaOGCByAGA2Xw2yKXT4CzGRsx+U9AlGJXHJTSfZ4k+x02kMUQBrxMSJQCr7FB8ux2NVkpaQyM3RkoQKE7iyoP8Q9K96VkUSL3r/jHKKRA4ScoudVcmIuftQUwFXbPi+jtuGWKdZnzsnrecn3UXZuOAMSCHas2BI4Mvkjy2clS28srsRIo+gkQliCew5Tb7ZJF0yuJCYtyGUzvv3NBz8iXuxVlJ6Q8xy5bNUsi0yl7aN65dQLLlkAXYHqejG7wKP1M2s6cOHLkKzQ7B1xGXDrpAT5y9brXBWny6Vvw0sNYRQDmsiq77TP7TZK01+gU9VtlqP1Hpop/G4hiUPaPxC2Q7QqMSgIKORep3i39cStWXfc9KllJ4NaMtIhyMHAVSKY0le2yLakc5Kr9AQBV9UPVQjccIvHHljdsH1+zEtCcvpe4aChKp6tJTDszm/VJAFbEdyecwGlvpKkYv5ZOVT7KrmgU/8HGkHz1OLc7sbVifsYq/pjJCx3c4+SJyFHnIbBHoRQ6xKzgipHdx3TVRktBVjt8ER6BGo8txnqF8j3esvHH7d4ZaI6Vq0Wl9zJOm47iDtewHw7R3KFg4cqSIMOEboyyhj6ytGLviqbK8UTk3JsuAhZBanFJH0PSVXy6bnbr69o5qvR7pc1HtC719OMVIL0u9yLHsA1sfMbMfxiGm/z1HxD/MRsFSnikuTvQk5yxE8pmVN2zvUbkHWqLKZlwzrNxlkdeEB1feuL07bJv9sHDkkPI1Gzm41R8Fjj9w0RlD21Kssl0NifTNB3WLiCo/3YKG4ef34y9BswcuXH9h2faya7fuVVevI+gSoOsswV0APTduB/WzFbAot+RJusxBYfhKC6K6N8/FCZ5HrCP9HwVGy5JTrFbsEfDu1Etq9IJZCoyFcticUhBMZi/g+RwtM44btsVQa5ebNdwaWWX7QjI3A46JHlCb83ULIRGzq/dfsP5fle0f9aFtOupD265R4DRSamdEvubO99ARCrzwid9f14vcQbs8IkwFa1CtZJlMA0+UIbhM4EheZ9tKR7XeOHIAsDGN6AnszmUxFhgB5jAG5ND9Zs29HtlXkU/18MHGBlFldA3CDTxyVtD4JcA1FrIJOUdqRR5fEXTz/vPXHxSzufzD276sWi9Xrf+BGi9qoy6rjfGCntkmW0cSuMmOuPx3YSRz42thA8lqbmWbV27Z8bVh1ya309UMUtKyEiULeATYkUE5pq6+/TFgd6atbuNvhPah5Q6rbFeZf2tOLiFvQNW2xupIQVr9NDuCxnfWSNq+77zZX+/va8X1dzysoF9RrXfVB0Lt7CzHbdR9rEXalWM0oJFvsiYVfN49MnOp5QtuVdBVw65Lzxq1bTprPs7QKrBWdSRRDmK1uiQLZCt3Q06HRo7q8lt2YzzUGNQU5Y303JJ9w1XoIl8m2iCgcZeDmxSOMeNz+8+f/eC+TbM9kfErb9geVnx0+1XAuqwCOiXSQXLHvY5AmdqkB9k6m+I5PDI/2zLi7w8R9LurFugxVUiZ9YUQDBxpbAVUe40wZduOn5xqxGL5ZrYrC+Cp/AEe/4DLN4ASi3GW0O0VFuMAfZygwHnAnXvPOf0F/X2u2rLji9ayn1fg86EbIhXo01gwuxdJbgltbBUJMUoTv1M7srYlBf3eyht3LEjNfOJtpy0DjnM5vKFaeb5HBlsBIqYmPR/iolXtylXQUU3ou9yR5mzFHV3ZwkjssyfjPTdAUTckflpEqb3KKr6579zTf62/35U3bP8HSa+1lr1Xou5HjuUf3rZXgfmq7WZ6p5KuTqZh5Wgx5YQv1frgqi07BnKqPSVUdnzzh2UVuWpXbqU9cihHHoxyGYJ06jSSzAFkW4f/Cx31aqweAe4yQl+2e5PgQ7NvOUQPFDhGgb/a947Tr9137ulTZderb9oZVm3ZcYVqzSpoxSHHVsg6TWacNVSqsbW4v+ebwLtHWot+kGayb6YUdoMj4mgF4vphLMhhhcxR6vbx2YipkeJe96VAY/kMKYZT3XiPGUlwBRpjGQ25jXw5sSCzzKKqdmQBIegC1bpz7znrnt8/hDWfunMn8CuP/d4v9Zljubc0tmWEyBpPohjdTEn2WGVvWLVlx0iF2w5aGsW7VVQXrn9IRMQeXvWxHXufpomBYFwyR05RyBFhzmbECQcuXN8aus2gXc4qrO1+iKxBZENY/KB4L7GR/JEjicsqbtZWLHZnAJWdivjm3nNO/9X+caz51J0Pr/nUnb3CY9CuJnE69RfIXlZLlxS5eitp08obt+/qb3tUsMpmGttGsQTxv7GwFBifzDEnL2ziDjN/1LI2ZscO3ab4DhBydJNrQKGgTCocXeUzF4qhFNKy/aLxAxXPxHOA/7r37ev+ZO/b1/WwmUPMd1fOqPc649Y49NwJmfwq/3nVlh2fHHr+T7U06XLh8p69LHwvoFhLP4xJ5oiqkzywBRofQtT9h5Y7pq65fR9mczmQKJPuxpPqv2ejlZqThA8ls5RC4yv8EPK/ySzpQgV27HnbaSc9xXx3uWZWXpdVRKElzOR7wGJU95mmnGtDpfNejAPGghzLrt36KNJjPacpW4EMa1WjayyWm2k0F4j9FIal/LyRCbMrX90k2EK2OThbMo/SSv+S2f3VVcu+tedtp/3rQ45LfAezy8yoe1bQrJS3HkH8xqqP7dg9ytyfEsxmHBMiWyTxSRiXX8WbHRfMZwdZJnGk4z3irZFiV1kOIZJSspGtpCbZs1rKH4XZ3X00TXwFDRI35nLcrR464TkE/vuet5529Z63ndbjX1l5w3atuP6Oy1VrFvGtTCEb6jUnad2qj+/4+kjzfvp1SRFgDYJ7mOC4DGCw0KSmAqyyOdX6KdcKgFgvLO7HaIawil0KhTk+xUtEyhG/0wTYqLFpCCiMZBl5uiEH2ZTUzTPTvShcjv+L7V9sZq8C1vWPb+WWHTuBlz9x9rp/YRU/p45Wgr4E3Lb64zuHvlNtENjz706rIIUvugEsU+mFp0CWMDbkkJoEp8zDIYXhjxguKO51alT6Wdw93fAP98g2ho6YiWfZUulJy+4295NetS3bQRCJRJPtJ1Hl5bTH3/KaZatv2nlIVXTlDdu/AHxhpDkOC8axQFsBTIX25QE/YwgsdhgfW8lXivaZBOIpHDWWdFcfHz8IKTwRqCcp2SlFtgMU9bqKGVetaC8pI8edRLuQl0zy4ckQYwlgugfBE9Xz2zptgfmxJYyNcgDz8iBaGkk6lUcaTSAV30c6gLFMKcjYrZw5nN99KdnRR4MAaXOtivEZVKADIUdv5TKRRe2v7MyiUINhwSF3Y4NU51yyJlk7GTmssj2hq7EV6B8b5YhspTBMmZuuDWB6//nrh+5r2Z/cXivwXVdHs8Ux2zNE6ZX1WIkcM1GkMeR4h6JmRmkniInN1iAIlMlJ14+6LuMGSTP54LULG088MPOrP7FTT/72cDBObSVfY97UJM0awDJJzxutWWWbQmnddDnBqUmDlL2Ww+YFDtZYspZzMNWAZNQS3wY+MtrYxw9W2XRZRbnHrsL41FgYsyqbQwV9E+hxDI2osdjf9VKjxk9StRpKle0UpcPN5ZAijC50Q/ak5oL3pb3EES4KeFslnbb6pp3jt1WMDjO+xg7xIGisaiyMU5U1diP2SFrVqIdGzkCLyPGNoRsWn0Vc6upaqENTPMUKVTZRAJd75IJsiTBmOcM9q7Gu5Yg9wC4F3Y3xbeAvV39i593jWp+xQbo/Vlh2ETgrZQHXZxwKxoYcy67dqv0XrJ/H7OTsQneqEanISJRj2Qe2fnP/Beu/jPjnjR5KNorlkMCiEJsjSOg2lCHEwF4RmMPsbox7DO4Buwe4G+P+VR9bWHTW4QDl+2NTcldhjNaYYkcdxqmtYMYc4mQVwmiRXD16MRfxaxhfUs2LyjAzw5BCUxs0aTJVZY8L7sG4B3GPjLvN7B7g3pU3bn9igdNcMnj8za8xxIwoUzSihZfWeK2jMGbkkNJV5jnDvMkJURi95PVRH9z60L5Ns6eCLkC8DbOfAEzSfVbZPRJ++u9Bumf59dvHeoKOFLCWrQVWSkX8bGXIMls5gikHzGeJ32MoG9VzQWWgln942z8Cf5D+se/c01srrrtjUUzURzDMuCU0R6xkodpgjLEcMF5tpaleF9RzzUayF4y1RtjyjzzrEAOkKIyqcBI2Dzuq9cNxdjde5PBYAjPPlU1mbAHM7D9vdrz9PctA4vluiKlaVY8rQIEHVn/yzvAkr44E40aO+7IZukGKCGZHYXbqWPt7tkFRNaAs8QRglf3fcXc3VuSQ+HvgISg0ztKDKr1unP09m+Dxt7xmJcYvg/uD6AnLDHVYeMpDH4wVOY764NYa43Ne5bf0cKayR2/df8H6Fz59SxPoBzP+CLFSSj4fvB5adgf85bj7HL8MEOt15hSAnBSOCEsAAAQOSURBVFwdI72PJujP922aPTgXZAJPCo+/5TWvBbuozKbzigIJ/teaT95577j7XQwBcYcZP/S4G0sGMXWCe0dfifTVfZtGu0Li2QSPv/k1rcfe9EvvA/5bmV4JyZeUwuysGj/VgB4f5Phg36bZq6xll5RBNJ5wVDiMuoivUdkXkR6J0VrFiIoQPtzP1Bh7XK/HUyLMzNwqGzoh3z3XPMdU0yyw1IQMWo4DyaMrr8HIkWGxGHEjTHl0YnqejLdxqO7v6DfIx9ABi1bO3iiuXA0wuk1ONrPTFHQciZU0JTcpd+4JxMtWf2Lnd4fapAFgUZBj//nrl6sOX8TsFUDjACtD+FM0uG96Ezbet2nuJfUbiCgWsSyVkIxtpQe2attB4YI9BdaKbj3fJdSxhniT5pjG1LNUpZu4+DRn01UxI69dNRmAycnncSkp/BAa5G3cw0VMiXfncbK+HqEbPKD4d1bftPMzI27VU8KiIAfA/vNmf1Lib804xk+wb05hUo+QTrHRxFT03WaQbSZ54SrLJ/6gGXnEuQf9+M43fszexfdX+4vbuxEyR73nu1obQVuKpTCdUvmYc2h8Xx/Jk9x/GEhu9x5qkyyfoQ7Zw+2hBlWrQkFbVn9i52JcRwosjswBwFEf2vY9jN8FsqXUI7P6N7U5QeDRZMEpR74VIFHU/k11J1+5GTm/1ttLCBGanx57kthF7CPl3+bKyKnBnBxVPMtVDUUOfs5jzZStGWOea4kYzia9LSv6Ld7JiFGYylXrW8D5Q2/MELCoFsvlH9r21wq8naC9QJPX4TxbDbL0LIbz8oLvZ8rhG29NDKjnzjqC5GCj4mTn2uxey6NPBsqRVdCkSjrVKctLpZNblHV08t5ANgAWMkIxf6CJcvf1wN3wRRwMDaJlT2z8806hX139iZ1Pe2HPQmDRzdnLP7LtBir7Wcx2WMvT4ck/eyTN8jTS+52y3EJTWqqpagxkKpEjo/yHL6pHkalBIN+sql0dFETklQUzKykE4qLwWwxAgoNPvSNNHp71JFLl7/axpxyl5ksQlMIT2AtcCKxb88k7R76NYlBYNJmjH/adO1shvZ3K3g+saSLGGzG/DNiBPqFR+Wu98orPIuet0ESkO1IUsocnY1NuZJ8GUAYRIbLw6FpFA4lNJS0iC6Nlucqq+Gr6jiNATifgEDKK9f6uoO1W2VtX37Rz7PaMJ4PDhhwO+zbNtoGfRjoVcSrGqxQisnj0WBI9olDaySWR5aWdyhC/MqkHkPXNqIw/JajgI0WCVEH2q6lKjqhlQdkCWdQTaNPTWWq3ZVK6cyULqI5YWSBFViDWIRD+u4i7gLswvrb6pp0/GsPyT2ACE5jABCYwgQlMYAITmMAEJjCBCUxgAhMo4f8Da5+jWrQcB5wAAAAASUVORK5CYII="/>
    </defs>
</svg>
```

**Comment by whmii** [comment]
@tysongach you break my ❤️

**Comment by whmii** [comment]
totally fine to reject this but It would be great to see some movement on this. I would prefer to launch the new site for neat.bourbon.io after the one for bourbon.io since I don't want to steal your thunder. 👍

**Comment by tysongach** [comment]
@whmii You should feel free to do your thing with Neat. No thunder will be stolen. Go for it!

**Pull request closed without merging**
