### PR TITLE
Remove obsolete navigation link

### PR DESCRIPTION
**Pull request by suy**

### CODE REVIEW

**Comment by tysongach** [comment]
Actually, the [Prefixer](http://bourbon.io/docs/#prefixer) still exists, the link is just wrong. It should be `#prefixer`, not `#prefixer-settings`.

Can you change to `<li><a href="#prefixer">Prefixer</a></li>` and I’ll merge it in?

Thanks!

**Comment by suy** [comment]
Sorry, it's late here and I might be sleepy, but isn't that link already there? In the commit is the line just below the removed line. I was initially going to fix the link to point to #global-prefixer, but I saw that was already below in the "Settings" section.

**Comment by tysongach** [comment]
Ah, yes! You’re correct. Thanks!

**Comment by suy** [comment]
El Friday 02 January 2015, Tyson Gach escribió:
> Ah, yes! You’re correct. Thanks!

Thank you for Bourbon. :)

**Pull request merged**
