### PR TITLE
Bourbon family lint!

### PR DESCRIPTION
**Pull request by mmwtsn**
## Description
I inadvertently linted my entire vendor directory last week while setting up Gulp on a project. Bourbon threw quite a few errors! This is the result of running SCSS-Lint over Bourbon.

This pull request intentionally violates the contributing guidelines for the time being. I thought this format would make it easier to review changes relative to their respective SCSS-Lint rules. It should make reversions easier as well if we decide a different setting is preferable. I'm happy to squash these down to a single commit if you decide to merge it in.

## SCSS Config
I tried to keep things in line with the [Thoughtbot style guide](https://github.com/thoughtbot/guides/tree/master/style#sass) as much as possible and came up with the following [SCSS-Lint config](https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md) as a base:

```yaml
linters:
  ElsePlacement:
    style: new_line
  LeadingZero:
    style: include_zero
  SelectorDepth:
    max_depth: 6
  StringQuotes:
    style: double_quotes
  TrailingZero:
    enabled: false
  UnnecessaryMantissa:
    enabled: false
```

I also disabled `VendorPrefixes` and the `Space*` family as the former was not applicable here and the latter was largely noise due to white space alignment across multiple files. If a SCSS-Lint config can be agreed upon (and you find this useful) I'll open pull requests for Neat and Bitters.

## Ignored Warnings
There were a few warnings that I ignored:

### Comment
C-style comment header seemed harmless enough at `_bourbon.scss:0`.

### DuplicateProperty
Duplication intentional at `css3/_background.scss:54` and `css3/_background-image.scss:41`.

### ElsePlacement
Ignored one line `@if` and `@else if` on `addons/_directional-values.scss:[35, 36, 37, 88]`. 

### Indentation
This is a tricky one as so many lines are indented with readability in mind.

Given that, the folowing were ignored:

- `css3/_background-image.scss:20`
- `css3/_background.scss:[23, 40, 46]`
- `css3/_border-image.scss:[18, 35, 41, 49, 50]`
- `css3/_transition.scss:[31, 32, 45, 46, 61, 62, 63]`

### NameFormat
Should the preference for lowercase variable names be ignored for single letter
variables?

Private function names were ignored. This feature should land in the next release of SCSS-Lint.

### PropertySortOrder
This one could probably use a patch back up at SCSS-Lint. Ignored a warning requesting that vendor-prefixed be alphabetized along with non-vendor-prefixed properties in `css3/_image-rendering.scss:4`. Also ignored a warning to alphabetize in `css3/_transition.scss:44` in preference for visual alignment here due to lack of properties.

### StringQuotes
Are they necessary in `css3/_radial-gradient.scss`?

### TrailingSemicolon
Ignored warnings for `addons/_directional-values.scss:[29, 30, 31, 32, 34, 35, 36, 37]` because the parser seemed a bit confused by this file.

### CODE REVIEW

**Comment by tysongach** [comment]
@mmwtsn Can you add the SCSS-Lint config file to the PR (the one from Neat)?

**Comment by mmwtsn** [comment]
@tysongach SCSS-Lint config added!

One note on the config file: the [default value for `ElsePlacement`](https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#elseplacement) disagrees with the majority of how Bourbon is written. One liners aside, only two files placed their `@else` statements on the same line as the closing curly brace. Everywhere else they were dropped onto a new line. Might be worth flipping that value to `style: new_line`.

**Comment by tysongach** [comment]
Merged. Thanks so much for your work on this, @mmwtsn!

**Comment by mmwtsn** [comment]
Awesome. Thanks @tysongach!

**Pull request closed without merging**
