### PR TITLE
Division via / is deprecated and raises warnings

### LINKED ISSUE #1106: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.
## Description

Using SASS >= 1.33.0 produces the following warnings when compiling:

```
: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($v1, $ratio)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
113 │         $v1: ($v1 / $ratio);
    │               ^^^^^^^^^^^^
    ╵
    node_modules\bourbon\core\bourbon\library\_modular-scale.scss 113:15  modular-scale()
    resources\scss\settings\_typography.scss 48:24                        @import
    resources\scss\settings\__index.scss 13:9                             @import
    resources\scss\main.scss 16:9                                         root stylesheet

: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($value, $value * 0 + 1)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
16 │   @return ($value / ($value * 0 + 1));
   │            ^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules\bourbon\core\bourbon\library\_strip-unit.scss 16:12  strip-unit()
    resources\scss\elements\_typography.scss 20:33                    @content
    resources\scss\tools\_mixins.scss 71:3                            mq()
    resources\scss\elements\_typography.scss 19:2                     @import
    resources\scss\elements\__index.scss 13:9                         @import
    resources\scss\main.scss 19:9                                     root stylesheet

: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($width, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
70 │       border-width: $height ($width / 2) 0;
   │                              ^^^^^^^^^^
   ╵
    node_modules\bourbon\core\bourbon\library\_triangle.scss 70:30  triangle()
    resources\scss\components\_sub-menu.scss 92:4                   @import
    resources\scss\components\__index.scss 19:9                     @import
    resources\scss\main.scss 21:9                                   root stylesheet

: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($width, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
58 │       border-width: 0 ($width / 2) $height;
   │                        ^^^^^^^^^^
   ╵
    node_modules\bourbon\core\bourbon\library\_triangle.scss 58:24  triangle()
    resources\scss\components\_sub-menu.scss 99:5                   @import
    resources\scss\components\__index.scss 19:9                     @import
    resources\scss\main.scss 21:9                                   root stylesheet
```

## Development Environment

- Bourbon version: 7.0.0
- Webpack version: 5.38.1

### PR DESCRIPTION
**Pull request by jclusso**
Ran the SASS migration tool for division so the deprecation warnings stop being thrown. This should resolve #1106.

### CODE REVIEW

**Comment by jclusso** [comment]
It seems that hound is complaining about the structure of the code which I didn't change. I'm going to leave that alone since I don't 100% know how to fix it. Hopefully it can be accepted as is since it's unrelated.

**Comment by jclusso** [comment]
Checking in to see if this can be merged?

**Comment by joepagan** [comment]
Sorry to notify you @tysongach as you appear to be the most activity on this repo in recent history. Could you help?

**Comment by tysongach** [comment]
I wish I could help, but I longer work at thoughtbot and am no longer involved in this project (I no longer have push access).

**Comment by joepagan** [comment]
@mike-burns looks like you've committed before & still work at thoughtbot, can you help sir or ask someone there who can?

**Comment by vendelal** [comment]
@joepagan hi! thanks for opening this PR and @mike-burns thanks for bringing this to my attention. I'll review this and the hound warnings and get this merged for ya

**Comment by joepagan** [comment]
@vendelal thanks for the response, have you had an opportunity to review this yet?

**Comment by Philip-Carneiro** [comment]
Hi @vendelal, did you had an opportunity to review this yet? Could you tag someone who can do it?
Thank you

**Review by vendelal — APPROVED** [review]

**Comment by joepagan** [comment]
@vendelal any chance of a release?

**Pull request merged**
