### PR TITLE
Add segment tracking

### PR DESCRIPTION
**Pull request by drapergeek**
* Remove Google Analytics, segment will send that same data over

### CODE REVIEW

**Comment by creuter** [comment]
:+1:

**Comment by tysongach** [comment]
@drapergeek This is great! Thanks. How do we access Segment for Bourbon? Is it in our 1Password?

**Comment by tysongach** [comment]
@drapergeek Ping ^

**Comment by drapergeek** [comment]
@tysongach Seems to be invite only on the thoughtbot account. I sent you an invite, sorry for missing for the first notification!

**Pull request merged**
