### PR TITLE
Update docs for font stacks

### PR DESCRIPTION
**Pull request by tysongach**
[Related PR](https://github.com/thoughtbot/bourbon/pull/644)

### CODE REVIEW

**Comment by joshuaogle** [comment]
I like it. But can we do a `git rename` instead of just renaming so it maintains history?

**Comment by tysongach** [comment]
@joshuaogle For some reason GitHub is not picking up on `git mv` for me…

**Comment by joshuaogle** [comment]
Oops, I did mean `git mv`. You may need to rename it back the regular way and then do it. I'd like to maintain that, but :+1:

**Comment by tysongach** [comment]
@joshuaogle Man, I tried it all (reverting back and force pushing back here, new commit, rebasing and squashing) but `mv` is just not working for me. It shows as `renamed` locally, but not here on GitHub. :cry:

**Pull request merged**
