### PR TITLE
Update prefixer mixin and remove spec option

### PR DESCRIPTION
**Pull request by HugoGiraudel**
Regarding #361.

I updated the `prefixer` mixin. I added an extra check in the `calc` mixin. I removed the `spec` prefix altogether.

That's pretty much it. Did I miss something?

### CODE REVIEW

**Comment by kaishin** [comment]
I don't think I can handle this soon. Anyone who feels like he can tackle it please do.

**Comment by tysongach** [comment]
**Update:** This is planned for 4.2.0. Thanks for effort, @HugoGiraudel!

Couple of notes:

I’m going to change the `$prefixes` variable name in the settings to `$global-prefixes`. This fixes a bug because `$prefixes` is already used as an argument when calling the `prefixer` mixin:

```scss
$global-prefixes: (
  "webkit": true,
  "moz": true,
  "ms": true,
  "o": true
) !default;
```

And then the `prefixer` mixin will be this:

```scss
@mixin prefixer($property, $value, $prefixes: ()) {
  @each $prefix in $prefixes {
    @if not map-has-key($global-prefixes, $prefix) {
      @warn "Unrecognized prefix: `#{$prefix}`.";
    }

    @if map-get($global-prefixes, $prefix) == true {
      #{"-" + $prefix + "-" + $property}: $value;
    }
  }

  #{$property}: $value;
}
```


Secondly, I’m going to change the `@if` statement in the `prefixer` mixin:

```scss
@if not map-has-key($global-prefixes, $prefix)
```

…to:

```scss
@if map-has-key($global-prefixes, $prefix) == false
```

…for LibSass compatibility.

Let me know if you have any thoughts on these changes.

**Comment by HugoGiraudel** [comment]
```scss
@if map-get($global-prefixes, $prefix) == true {
  #{"-" + $prefix + "-" + $property}: $value;
}
```

Do not use `== true`.

```scss
@if map-has-key($global-prefixes, $prefix) == false
```

LibSass now [supports]() the `not` operator.

**Comment by tysongach** [comment]
Thanks @HugoGiraudel, will do!

Totally forgot LibSass 3.1 implemented the `not` operator.

**Comment by HugoGiraudel** [comment]
Aside of that, it looks nice. Just realised my previous comment was a bit tough, not intended. :P

**Comment by tysongach** [comment]
@HugoGiraudel No worries. Always appreciate the help.

**Comment by HugoGiraudel** [comment]
Anytime for Bourbon, Tyson. ;)

**Comment by tysongach** [comment]
Merged.

**Pull request closed without merging**
