### PR TITLE
Adds :invalid pseudo-class for $all-text-inputs

### PR DESCRIPTION
**Pull request by tesujimath**
Companion pull request for the feature resolving #804.

### CODE REVIEW

**Comment by tesujimath** [comment]
I see hound is complaining, but my code matches the existing style exactly.  Is this blocking the merge?

**Comment by joshuaogle** [comment]
It's not blocking the merge necessarily. It's acceptable here (to me, anyway).

Looks great! :+1:

**Comment by joshuaogle** [comment]
*Note*: We should add some tests. It doesn't need to be in this PR, but we should get it in ASAP

**Comment by tysongach** [comment]
@tesujimath Thanks for the PR! Since we’re including this new `$all-text-inputs-invalid` variable in our 5.0 release, documentation will be handled by SassDoc via source comments, and no longer via the Jekyll site found in `gh-pages`. Based on that, I’m going to close this PR and the new variable will be indicated in our new documentation site.

**Pull request closed without merging**
