### PR TITLE
str-slice(): index of first character in a Sass string starts at 1

### PR DESCRIPTION
**Pull request by robocoder**
http://sass-lang.com/documentation/Sass/Script/Functions.html#str_slice-instance_method

### CODE REVIEW

**Comment by tysongach** [comment]
@robocoder Is there a specific issue you ran into that prompted you to make this change? I can't seem to reproduce any bugs that this is causing as is…or for that matter, see any change in output by introducing this change.

**Comment by robocoder** [comment]
Ran into it with the php version of the scss compiler. It's been fixed there, but reported it here so you don't rely on undocumented behavior.

**Comment by tysongach** [comment]
Gotcha, thanks!

In some real quick testing, it looks like Sass is smart enough to accept both `0` and `1` to grab the first character.

**Comment by tysongach** [comment]
Merged. Thanks!

**Pull request closed without merging**
